### ISSUE TITLE
Unable to build project after adding this package

### ISSUE THREAD

**Issue by cjholowatyj** [unplugin/unplugin-vue-markdown#43]
### Describe the bug

Upon attempting to use `unplugin-vue-markdown` within my project, I get the following error during build time:

```
"extname" is not exported by "__vite-browser-external:path", imported by "node_modules/.pnpm/@rollup+pluginutils@5.1.0/node_modules/@rollup/pluginutils/dist/es/index.js".
file: node_modules/.pnpm/@rollup+pluginutils@5.1.0/node_modules/@rollup/pluginutils/dist/es/index.js:1:9
1: import { extname, win32, posix, isAbsolute, resolve } from 'path';
            ^
```

If I add `vite-plugin-node-polyfills` to my Vite config and polyfill `path` then I get the following error:

```
"createRequire" is not exported by "__vite-browser-external:module", imported by "node_modules/.pnpm/unplugin-vue-markdown@0.26.0_vite@4.5.2/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js".
file: node_modules/.pnpm/unplugin-vue-markdown@0.26.0_vite@4.5.2/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js:259:9
259: import { createRequire } from "module";
              ^
```

If I then polyfill `module` I get the following error:

```
"createRequire" is not exported by "node_modules/.pnpm/node-stdlib-browser@1.2.0/node_modules/node-stdlib-browser/esm/mock/empty.js", imported by "node_modules/.pnpm/unplugin-vue-markdown@0.26.0_vite@4.5.2/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js".
file: node_modules/.pnpm/unplugin-vue-markdown@0.26.0_vite@4.5.2/node_modules/unplugin-vue-markdown/dist/chunk-XC4FHL6S.js:259:9
259: import { createRequire } from "module";
              ^
```

How do I get over this roadblock to using `unplugin-vue-markdown` within my project?

_*PS*_ this is my current dev stack:
`Laravel 10` / `InertiaJS 1` / `VueJS 3` / `ViteJS 4` / `TailwindCSS 3` / `Vitest 0.31` / `VitePress 1` / `Typescript` / `SSR` / `FontAwesome Pro 6` / `Ploi.io` / `Qodana` / `Cypress` / `ImgIX` / `HubSpot` / `SendGrid` / `SignEasy` / `Stripe`

### Reproduction

would have started a discussion here to get support, but there's no discussion tab here :(

### System Info

```Shell
System:
    OS: macOS 14.4
    CPU: (8) arm64 Apple M1 Pro
    Memory: 62.33 MB / 16.00 GB
    Shell: 5.2.15 - /opt/homebrew/bin/bash
  Binaries:
    Node: 21.6.2 - /opt/homebrew/bin/node
    Yarn: 1.22.21 - /opt/homebrew/bin/yarn
    npm: 10.2.4 - /opt/homebrew/bin/npm
    pnpm: 8.6.1 - ~/Library/pnpm/pnpm
  Browsers:
    Chrome: 122.0.6261.112
    Safari: 17.4
```

### Used Package Manager

pnpm

### Validations

- [X] Follow our [Code of Conduct](https://github.com/antfu/.github/blob/main/CODE_OF_CONDUCT.md)
- [X] Read the [Contributing Guide](https://github.com/antfu/contribute).
- [X] Check that there isn't already an issue that reports the same bug to avoid creating a duplicate.
- [X] Check that this is a concrete bug. For Q&A, please open a GitHub Discussion instead.
- [X] The provided reproduction is a [minimal reproducible](https://stackoverflow.com/help/minimal-reproducible-example) of the bug.

**Comment by s-light** [comment]
i think i just had a very similar bug:

```
$ quasar dev

 .d88888b.
d88P" "Y88b
888     888
888     888 888  888  8888b.  .d8888b   8888b.  888d888
888     888 888  888     "88b 88K          "88b 888P"
888 Y8b 888 888  888 .d888888 "Y8888b. .d888888 888
Y88b.Y8b88P Y88b 888 888  888      X88 888  888 888
 "Y888888"   "Y88888 "Y888888  88888P' "Y888888 888
       Y8b

node:internal/modules/esm/resolve:303
  return new ERR_PACKAGE_PATH_NOT_EXPORTED(
         ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: No "exports" main defined in /home/stefan/myproject/node_modules/markdown-it-async/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:303:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:593:13)
    at resolveExports (node:internal/modules/cjs/loader:591:36)
    at Module._findPath (node:internal/modules/cjs/loader:668:31)
    at Module._resolveFilename (node:internal/modules/cjs/loader:1130:27)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at /home/stefan/myproject/node_modules/unplugin-vue-markdown/dist/chunk-QCQKKB2O.cjs:118:96
    at async /home/stefan/myproject/node_modules/unplugin-vue-markdown/dist/chunk-QCQKKB2O.cjs:118:37 {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
}

Node.js v20.11.0
```

maybe its something different...

would love to test this out in my project..

**Comment by s-light** [comment]
after upgrading my full stack it is working (partly - but that is another question i have first to understand..)

**Comment by benjivm** [comment]
@s-light what do you mean by "upgrading your full stack?", all packages in my package.json file are up to date, but I am also receiving the same error you did:

```
No "exports" main defined in ./node_modules/markdown-it-async/package.json
    at exportsNotFound (node:internal/modules/esm/resolve:314:10)
    at packageExportsResolve (node:internal/modules/esm/resolve:604:13)
    at resolveExports (node:internal/modules/cjs/loader:653:36)
    at Function._findPath (node:internal/modules/cjs/loader:742:31)
    at Function._resolveFilename (node:internal/modules/cjs/loader:1380:27)
    at defaultResolveImpl (node:internal/modules/cjs/loader:1050:19)
    at resolveForCJSWithHooks (node:internal/modules/cjs/loader:1055:22)
    at Function._load (node:internal/modules/cjs/loader:1204:37)
    at TracingChannel.traceSync (node:diagnostics_channel:322:14)
    at wrapModuleLoad (node:internal/modules/cjs/loader:234:24) {
  code: 'ERR_PACKAGE_PATH_NOT_EXPORTED'
```

Dropping down to v28.1.0 fixes it.

**Comment by antfu** [comment]
We temporarily closed this due to the lack of enough information. We could not identify whether it was a bug or a userland misconfiguration with the given info.
Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) to reopen the issue.
Thanks.

> [Why reproduction is required](https://antfu.me/posts/why-reproductions-are-required)
